name: Release to Sonatype

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write  # sbt-release will create tags and push commits

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      # Trigger Publish.settings ReleaseToSonatype branch
      USERNAME: ${{ github.actor }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      # gpg on headless runners
      GPG_TTY: /dev/pts/0
    steps:
      - name: Checkout
      # sbt-release needs tags and full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: sbt

      - name: Cache Ivy and Coursier
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/**.sbt', '**/project/**.scala') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Import GPG private key
        shell: bash
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          printf "%s" "${GPG_SECRET}" | gpg --batch --import
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}

      - name: Show GPG keys (debug)
        if: always()
        run: |
          gpg --version
          gpg --list-keys || true
          gpg --list-secret-keys || true

      - name: Configure Git identity for release
        run: |
          git config user.email "ci@users.noreply.github.com"
          git config user.name "GitHub Actions Release Bot"

      - name: Run tests
        run: sbt "++2.13.16; test"

      - name: Release to Sonatype (bundle + close + release)
        run: sbt "release with-defaults"
